name: Statistic code analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DISPLAY: ":99.0"

  
permissions:
  contents: read

jobs:
  analysis:
    permissions:
      contents: read  # for pmd/pmd-github-action to determine modified files
      pull-requests: read  # for pmd/pmd-github-action to query PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: pmd/pmd-github-action@d9c1f3c5940cbf5923f1354e83fa858b4496ebaa # v2.0.0
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'src/main/java'
          rulesets: 'java-basic'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
    
